apiVersion: apps/v1
kind: Deployment
metadata:
  name: opentelemetry-collector
  namespace: default  # Adjust namespace as needed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opentelemetry-collector
  template:
    metadata:
      labels:
        app: opentelemetry-collector
    spec:
      containers:
        - name: opentelemetry-collector
          image: rajatbadola/otel-collector:latest
          ports:
          - containerPort: 4317  # gRPC OTLP
          - containerPort: 4318  # HTTP OTLP
---
apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  namespace: default  # Replace with the namespace where your pod is running
  labels:
    app: otel-collector
spec:
  selector:
    app: opentelemetry-collector  # Must match the label in your OpenTelemetry Collector pod
  ports:
    - protocol: TCP
      port: 4317          # This is the port exposed by the service
      targetPort: 4317    # This is the port on the pod
      name: grpc
    - port: 4318
      targetPort: 4318
      protocol: TCP
      name: http
  type: ClusterIP        # Adjust as needed; ClusterIP is for internal access
